# Generated by Django 5.2.6 on 2025-09-16 06:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Auction_Listing",
            new_name="Listing",
        ),
    ]
