# Generated by Django 5.2.6 on 2025-09-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_rename_auction_listing_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
