# Generated by Django 5.2.6 on 2025-09-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_remove_bid_id_remove_comment_id_bid_bid_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="listings.listing",
            ),
        ),
    ]
