# Generated by Django 5.2.6 on 2025-09-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_listing_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("fashion", "Fashion"),
                    ("home", "Home & Garden"),
                    ("vehicles", "Vehicles"),
                    ("collectibles", "Collectibles"),
                    ("sports", "Sports & Recreation"),
                    ("books", "Books & Media"),
                    ("art", "Art & Antiques"),
                    ("jewelry", "Jewelry & Watches"),
                    ("toys", "Toys & Games"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
