# Generated by Django 5.2.6 on 2025-09-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bid",
        ),
    ]
